version: '3'
services:
  frontend:
    container_name: front
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ./frontend
        target: /app
      - type: volume
        source: node_modules
        target: /app/node_modules
    command: npm run dev
  
  backend:
    container_name: back
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - 8000:8000
  
  test-db:
    container_name: test-db
    image: mysql:8.0
    platform: linux/x86_64
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: 'testdata'
      TZ: 'Asia/Tokyo'
    volumes:
      - test_mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 43306:3306

volumes:
  test_mysql_data:
  node_modules:
