on:
  push:

permissions: write-all

jobs:
  pytest_coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker images
        run: docker-compose build

      - name: Start Docker containers
        run: docker-compose up

      - name: Run Tests
        run: |
          docker container exec back poetry run pytest --cov --cov-branch --cov-report=term-missing --junitxml=pytest.xml test | tee pytest-coverage.txt

      - name: Pytest coverage comment
        uses: MishaKav/pytest-coverage-comment@main
        with:
          pytest-coverage-path: ./pytest-coverage.txt
          junitxml-path: ./pytest.xml
